package rollouts

import (
	"fmt"
	"os"
	"path/filepath"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	rbacv1 "k8s.io/api/rbac/v1"
	"sigs.k8s.io/yaml"
)

// The operator creates the Roles and ClusterRoles that Argo Rollouts runs with. Kubernetes' RBAC
// escalation prevention only lets a subject grant permissions it holds itself, so every rule the
// operator hands out must also be covered by the operator's own ClusterRole in config/rbac/role.yaml
// (generated by controller-gen from the kubebuilder markers in argorollouts_controller.go).
//
// When the two drift apart, an in-cluster deployment of the operator cannot reconcile any
// RolloutManager and fails with:
//
//	clusterroles.rbac.authorization.k8s.io "argo-rollouts" is forbidden: user "system:serviceaccount:..."
//	is attempting to grant RBAC permissions not currently held: ...
//
// The e2e tests run the operator out of cluster with an admin kubeconfig, where the escalation check
// never applies, so this unit test is what guards the invariant.
var _ = Describe("Operator RBAC", func() {

	loadOperatorClusterRole := func() rbacv1.ClusterRole {
		data, err := os.ReadFile(filepath.Join("..", "config", "rbac", "role.yaml"))
		Expect(err).ToNot(HaveOccurred())

		var role rbacv1.ClusterRole
		Expect(yaml.Unmarshal(data, &role)).To(Succeed())
		Expect(role.Rules).ToNot(BeEmpty())
		return role
	}

	// holds reports whether rules contain a rule covering group/resource/verb, honouring wildcards.
	holds := func(rules []rbacv1.PolicyRule, group, resource, verb string) bool {
		contains := func(list []string, want string) bool {
			for _, item := range list {
				if item == want || item == "*" {
					return true
				}
			}
			return false
		}
		for _, rule := range rules {
			if contains(rule.APIGroups, group) && contains(rule.Resources, resource) && contains(rule.Verbs, verb) {
				return true
			}
		}
		return false
	}

	// missing lists every group/resource/verb in granted that the operator's rules do not cover.
	missing := func(operator []rbacv1.PolicyRule, granted []rbacv1.PolicyRule) []string {
		var result []string
		for _, rule := range granted {
			for _, group := range rule.APIGroups {
				for _, resource := range rule.Resources {
					for _, verb := range rule.Verbs {
						if !holds(operator, group, resource, verb) {
							result = append(result, fmt.Sprintf("apiGroup %q, resource %q, verb %q", group, resource, verb))
						}
					}
				}
			}
		}
		return result
	}

	DescribeTable("the operator's ClusterRole holds every permission the operator grants",
		func(granted func() []rbacv1.PolicyRule) {
			operator := loadOperatorClusterRole().Rules

			Expect(missing(operator, granted())).To(BeEmpty(),
				"the operator grants permissions it does not hold; add them to the kubebuilder rbac markers "+
					"in controllers/argorollouts_controller.go and run 'make manifests bundle'")
		},
		Entry("Argo Rollouts controller rules (Role and ClusterRole)", GetPolicyRules),
		Entry("aggregate-to-admin ClusterRole rules", GetAggregateToAdminPolicyRules),
		Entry("aggregate-to-edit ClusterRole rules", GetAggregateToEditPolicyRules),
		Entry("aggregate-to-view ClusterRole rules", GetAggregateToViewPolicyRules),
	)
})
