name: Run upstream Argo-Rollouts E2E tests
on:
  push:
    branches:
      - 'main'
      - 'release-*'
  pull_request:
    branches:
      - '*'

jobs:

  test-e2e:
    name: Run end-to-end tests from upstream Argo Rollouts repo
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      matrix:
        k3s-version: [ v1.28.2 ]
        # k3s-version: [ v1.28.2, v1.27.6, v1.26.9 ]
    steps:
      - name: Install K3S
        run: |
          set -x
          curl -sfL https://get.k3s.io | sh -
          sudo chmod -R a+rw /etc/rancher/k3s
          sudo mkdir -p $HOME/.kube && sudo chown -R runner $HOME/.kube
          sudo k3s kubectl config view --raw > $HOME/.kube/config
          sudo chown runner $HOME/.kube/config
          sudo chmod go-r $HOME/.kube/config
          kubectl version
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v5.0.0
        with:
          go-version-file: './go.mod'          
      - name: GH actions workaround - Kill XSP4 process
        run: |
          sudo pkill mono || true
      - name: Add /usr/local/bin to PATH
        run: |
          echo "/usr/local/bin" >> $GITHUB_PATH
      - name: Download Go dependencies
        run: |
          go mod download
      - name: Run the Argo Rollouts E2E tests
        run: |
          set -o pipefail
          ./hack/run-upstream-argo-rollouts-e2e-tests.sh
